apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t03y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t03y
    app.kubernetes.io/part-of: test-app-167654861
  name: devfile-sample-t03y
  namespace: skhileri-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-t03y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-t03y
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:9e46b3bf44d7f2b9691aad9c214abc0d7fb18a1c4b64c8cc2d87fbdfca021e32
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
