apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t03y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t03y
    app.kubernetes.io/part-of: test-app-167654861
  name: devfile-sample-t03y
  namespace: skhileri-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-t03y
status:
  loadBalancer: {}
